### ISSUE TITLE
Stitching failed for images from overhead camera. 

### ISSUE THREAD

**Issue by trohit920** [AVINASH793/Panoramic-Image-Stitching-using-invariant-features#10]
Hey, thanks for the wonderful repo but it failed for over head images.
I tried using your repo for images captured from a rotating PTZ  Camera and the output result show only the images appended to each other.
FYI, Check below attached output and input images, any feedback or advice is really appreciated. 
![frame_8](https://github.com/Avinash793/panoramic-image-stitching/assets/30137687/21aa9779-212b-41c2-b461-a447abda5bb8)
![frame_9](https://github.com/Avinash793/panoramic-image-stitching/assets/30137687/ef981768-69e4-41f8-a9c4-99aba1feea0d)
![frame_10](https://github.com/Avinash793/panoramic-image-stitching/assets/30137687/28b33a9d-3ddf-4126-bb40-c3a6f3833013)
![frame_11](https://github.com/Avinash793/panoramic-image-stitching/assets/30137687/bf1675f3-5ff2-4927-9e40-6cc5930f48b5)
![panorama_image](https://github.com/Avinash793/panoramic-image-stitching/assets/30137687/1a533614-afc2-419f-adc1-2aced5f30e01)

**Comment by Avinash793** [comment]
@trohit920 sorry for delayed response. Are you still facing the issue?

**Comment by Avinash793** [comment]
@trohit920 Please let me know if you are still facing the same issue.
