### ISSUE TITLE
About Versions of software

### ISSUE THREAD

**Issue by gokes001** [AVINASH793/Panoramic-Image-Stitching-using-invariant-features#2]
Could you please give information about the version of python opencv you had used.

**Comment by AVINASH793** [comment]
Hi, I have used opencv version 3.3.0.

**Comment by philshem** [comment]
This is the output of my `pip freeze`

    imutils==0.5.3
    numpy==1.17.3
    opencv-contrib-python==3.4.2.16
    opencv-python==3.4.2.16

with Python 3.7.3, which is working for me.

but would be cool to add a `requirements.txt` file to the repo

    pip freeze > requirements.txt

**Comment by Anil515** [comment]
Sir when I am giving input like tajm1.jpg showing not defined

**Comment by AVINASH793** [comment]
@Anil515 Make sure you have image with name "tajm1.jpg" in your same directory where python code is present.

**Comment by Anil515** [comment]
Sir I was cloned has it is  and installed modules and run the stitch.py

**Comment by Anil515** [comment]
ImportError                               Traceback (most recent call
last)<ipython-input-1-73e2257f9809> in <module>()----> 1 from panorama
import Paranoma      2 import imutils      3 import cv2
ImportError: cannot import name 'Paranoma'

sir please help me out

**Comment by AVINASH793** [comment]
@Anil515 try to run as I suggested in README. Please go through it.
